import type { FormularioCotacao, TipoServicoCotacao } from '@/types/site/cotacao';

export const FORMULARIO_COTACAO_INICIAL: FormularioCotacao = {
  nome: '',
  empresa: '',
  cnpj: '',
  email: '',
  telefone: '',
  tipoServico: '',
  cidadeOrigem: '',
  ufOrigem: '',
  cidadeDestino: '',
  ufDestino: '',
  tipoCarga: '',
  pesoMedio: '',
  valorMercadoria: '',
  tipoVeiculo: '',
  cubagem: '',
  embarquesMes: '',
  produtoPerigoso: '',
  informacoesProdutoPerigoso: '',
  armazenagemServicoDesejado: '',
  armazenagemCidade: '',
  armazenagemUf: '',
  armazenagemVolumeAproximado: '',
  observacoes: '',
  aceitePrivacidade: false,
};

export const UFS = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
];

export const SOLUCOES_COTACAO: Array<{ value: Exclude<TipoServicoCotacao, ''>; label: string }> = [
  { value: 'TRANSPORTE_RODOVIARIO', label: 'Transporte rodoviário' },
  { value: 'ARMAZENAGEM', label: 'Armazenagem' },
  { value: 'OPERACAO_LOGISTICA', label: 'Operação logística' },
  { value: 'DISTRIBUICAO', label: 'Distribuição' },
  { value: 'OUTRO', label: 'Outro' },
];
